### ISSUE TITLE
Look into baking the ron files into the binary with `Config::load_bytes`

### ISSUE THREAD

**Issue by cdsupina** [amethyst/theta-wave#130]
The ron config and data files are currently not baked into the binary. When the build is compiled, the user should not have access to these files to modify.

https://www.reddit.com/r/rust/comments/m6a3yx/theta_wave_v014_foundations_update/gr6blwt/?context=3

**Comment by cruelnoise** [comment]
Hi, I don't know how to use git(hub) properly or contribute to projects and I also don't know if what I threw together is what you're actually looking for, but here it is if you're interested: https://github.com/cruelnoise/theta-wave/commit/04512b6362af9c7373006ce6468b511121a613c9

**Comment by cdsupina** [comment]
Thanks for the branch, that looks great! Go to the pull requests tab on your fork and request to merge your forked master branch with the base master branch for amethyst/theta-wave to start the review process.

I'll message you on discord so you can let me know if you need any more help.

**Comment by cdsupina** [comment]
Update: After reviewing #138, I like the idea of having the user able to access and modify the config files, but they still should not be able to edit the files in `assets/data`.
