### ISSUE TITLE
Give blasts a "range" using a TimeLimitComponent

### ISSUE THREAD

**Issue by cdsupina** [amethyst/theta-wave#155]
Currently blasts will travel until they reach a "despawn line" at a y-value above or below the arena. This is effectively inifinite range. Let's make the game more interesting by adding a finite range to fired blasts by giving them a `TimeLimitComponent`.

This will also allow us to add items to increase range in the future.

**Comment by AndreasHempel** [comment]
Spent some time today warming up to Rust, game development, and open source contributions by tackling this. Would appreciate comments on #166 @cdsupina.

**Comment by cdsupina** [comment]
I'll take a look!
