### ISSUE TITLE
Binary does not work for Ubuntu 16.04

### ISSUE THREAD

**Issue by eleidan** [amethyst/theta-wave#16]
```
$ ./space_shooter 
./space_shooter: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./space_shooter)
```

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

**Comment by eleidan** [comment]
Pretty common issue for so many Rust projects :-) As the binary is obtained on a Linux distribution with close to latest **libc** version.

Possible solution here is to build binary in, lets say, **Ubuntu 16.04 LTS**.

**Comment by cdsupina** [comment]
Yeah I created the build on an Arch system. I'm not currently using Ubuntu anywhere, but I plan on having a Ubuntu on a Jetson Nano within the next month. In the meantime if you or anybody else would like to build it on Ubuntu and send it here that would be great!

**Comment by cdsupina** [comment]
CI should check for this issue now.
