### ISSUE TITLE
Link in README is dead

### ISSUE THREAD

**Issue by Jazarro** [amethyst/theta-wave#25]
In the first paragraph of your readme, you [link](https://micronote.tech/2019/06/Space-Shooter-Game/) to your website. This link is dead; it now leads to a 404 page.

**Comment by cdsupina** [comment]
Thanks for raising the issue. I will update this in my dev branch. Until then you can view the write-up [here](https://micronote.tech/2019/09/Space-Shooter-Game/).

**Comment by cdsupina** [comment]
Removed altogether
