### ISSUE TITLE
Refactoring Motion2D

### ISSUE THREAD

**Issue by tigleym** [amethyst/theta-wave#91]
Entities whose Motion2D components with a `rigid_body` property set to true should be able to neglect any forces exerted on it. So if entity 'A' collides with an entity 'B' with `rigid_body`, entity B's Motion2D component will not be affected by the collision.

**Comment by tigleym** [comment]
Update: 

We'll break this issue down into smaller tasks since the goal is simplifying a lot of the existing motion2D logic and will require rewriting some systems responsible for handling entity motions. PRs related to the motion 2D refactoring should reference this issue.

**Comment by cdsupina** [comment]
#117
